#!/usr/bin/env node
// Writes shared/version.ts from the package.json version so the User-Agent constant
// never needs a manual bump. Runs as part of `npm run build`.
import { readFileSync, writeFileSync } from 'node:fs';

const { version } = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const target = new URL('../shared/version.ts', import.meta.url);
const content = `// Generated by scripts/sync-version.mjs from package.json. Do not edit.\nexport const PACKAGE_VERSION = '${version}';\n`;

let current = '';
try {
	current = readFileSync(target, 'utf8');
} catch {
	// First run: the file does not exist yet.
}
if (current !== content) writeFileSync(target, content);
